Expose connect and disconnect broker methods
astarte-platform/astarte-device-sdk-qt5 pull request #32
Opened 2021-11-02 15:38 UTC by harlem88

New methods in the AstarteDeviceSDK class:
- connectToBroker
- disconnectFromBroker

Signed-off-by: Antonio Gisondi <antonio.gisondi@secomind.com>

2021-11-08 15:14 UTC, rbino requested changes

2021-11-08 15:14 UTC, rbino commented on astarte-device-sdk/AstarteDeviceSDK.cpp
> +  return m_astarteTransport->connectToBroker();
`m_astarteTransport` is initialized asynchronously, so you should always check if it's `null` before calling methods on it

2021-11-08 15:14 UTC, rbino commented on astarte-device-sdk/AstarteDeviceSDK.cpp
> +  return m_astarteTransport->disconnectFromBroker();
See above

2021-11-08 15:14 UTC, rbino commented on astarte-transport/astartetransport.cpp
> +  return m_mqttBroker->connectToBroker();
`m_mqttBroker` could be `null`, check with `isNull()` before calling methods on it

2021-11-08 15:14 UTC, rbino commented on astarte-transport/astartetransport.cpp
> +  return m_mqttBroker->disconnectFromBroker();
See above

2021-11-12 17:20 UTC, bettio requested changes

2021-11-12 17:20 UTC, bettio commented on CHANGELOG.md
> +- Expose connect/disconnect broker methods in the SDK.
Let's separate Added and Changed with an empty line

2021-11-12 17:20 UTC, bettio commented on astarte-device-sdk/AstarteDeviceSDK.cpp
> +  if (!m_astarteTransport) {
maybe we should add a qDebug().
`qDebug() << "Not yet initialized, cannot connect to broker."`

2021-11-12 17:20 UTC, bettio commented on astarte-device-sdk/AstarteDeviceSDK.cpp
> +    return false;
qDebug() << "Not initialized, cannot disconnect from broker."

2021-11-12 17:20 UTC, bettio commented on astarte-device-sdk/AstarteDeviceSDK.h
> +    bool disconnectFromBroker();
I'm not 100% sure if we should mention here `Broker` or just find a more generic naming, such as `connectToAstarte()`.

2021-11-15 10:33 UTC, bettio approved these changes

2021-11-15 11:23 UTC, merged